// Package integrity computes and verifies artifact digests (sha1, sha256,
// sha512) and understands the SRI notation ("sha512-<base64>") that npm
// packuments use in their dist.integrity fields.
package integrity

import (
	"crypto/sha1"
	"crypto/sha256"
	"crypto/sha512"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"hash"
	"strings"
)

// Hash is an expected digest in canonical lowercase-hex form.
// The zero value means "no expectation".
type Hash struct {
	Algo string // "sha1", "sha256" or "sha512"
	Hex  string
}

// IsZero reports whether no digest expectation is set.
func (h Hash) IsZero() bool { return h.Algo == "" }

// String renders the digest as "<algo>:<hex>", or "none" for the zero value.
func (h Hash) String() string {
	if h.IsZero() {
		return "none"
	}
	return h.Algo + ":" + h.Hex
}

func newHasher(algo string) (hash.Hash, error) {
	switch algo {
	case "sha1":
		return sha1.New(), nil
	case "sha256":
		return sha256.New(), nil
	case "sha512":
		return sha512.New(), nil
	}
	return nil, fmt.Errorf("unsupported digest algorithm %q", algo)
}

// ParseSRI parses a Subresource Integrity string such as "sha512-<base64>".
// Both padded and unpadded base64 payloads are accepted, because both occur
// in the wild.
func ParseSRI(s string) (Hash, error) {
	algo, b64, ok := strings.Cut(s, "-")
	if !ok || algo == "" || b64 == "" {
		return Hash{}, fmt.Errorf("malformed SRI %q", s)
	}
	h, err := newHasher(algo)
	if err != nil {
		return Hash{}, err
	}
	raw, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		raw, err = base64.RawStdEncoding.DecodeString(b64)
	}
	if err != nil {
		return Hash{}, fmt.Errorf("malformed SRI %q: %v", s, err)
	}
	if len(raw) != h.Size() {
		return Hash{}, fmt.Errorf("SRI %q: digest is %d bytes, %s needs %d", s, len(raw), algo, h.Size())
	}
	return Hash{Algo: algo, Hex: hex.EncodeToString(raw)}, nil
}

// FromNpmDist picks the strongest digest advertised by an npm dist object:
// dist.integrity (usually sha512) wins over the legacy sha1 dist.shasum.
// Malformed fields are skipped rather than fatal — a mirror should still be
// able to cache a package whose metadata predates SRI.
func FromNpmDist(integritySRI, shasum string) Hash {
	if integritySRI != "" {
		if h, err := ParseSRI(integritySRI); err == nil {
			return h
		}
	}
	if len(shasum) == sha1.Size*2 {
		if _, err := hex.DecodeString(shasum); err == nil {
			return Hash{Algo: "sha1", Hex: strings.ToLower(shasum)}
		}
	}
	return Hash{}
}

// Digester accumulates a stream, verifying it against an expected digest
// while always producing a sha256 — the store's canonical sidecar digest.
type Digester struct {
	want  Hash
	wantH hash.Hash
	s256  hash.Hash
	n     int64
}

// NewDigester returns a Digester enforcing want (which may be the zero Hash
// to skip enforcement and only compute the canonical sha256).
func NewDigester(want Hash) (*Digester, error) {
	d := &Digester{want: want, s256: sha256.New()}
	if want.IsZero() {
		return d, nil
	}
	h, err := newHasher(want.Algo)
	if err != nil {
		return nil, err
	}
	raw, err := hex.DecodeString(want.Hex)
	if err != nil || len(raw) != h.Size() {
		return nil, fmt.Errorf("malformed %s digest %q", want.Algo, want.Hex)
	}
	if want.Algo != "sha256" {
		d.wantH = h // sha256 expectations reuse the canonical hasher
	}
	return d, nil
}

// Write implements io.Writer. It never fails.
func (d *Digester) Write(p []byte) (int, error) {
	d.s256.Write(p)
	if d.wantH != nil {
		d.wantH.Write(p)
	}
	d.n += int64(len(p))
	return len(p), nil
}

// Sum returns the canonical sha256 hex digest and the byte count, or an
// error when the accumulated stream does not match the expected digest.
func (d *Digester) Sum() (sha256hex string, size int64, err error) {
	got256 := hex.EncodeToString(d.s256.Sum(nil))
	if !d.want.IsZero() {
		got := got256
		if d.wantH != nil {
			got = hex.EncodeToString(d.wantH.Sum(nil))
		}
		if !strings.EqualFold(got, d.want.Hex) {
			return "", 0, fmt.Errorf("integrity mismatch: want %s:%s, got %s:%s",
				d.want.Algo, strings.ToLower(d.want.Hex), d.want.Algo, got)
		}
	}
	return got256, d.n, nil
}

// SHA256Hex returns the lowercase hex sha256 of b.
func SHA256Hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// SHA1Hex returns the lowercase hex sha1 of b (npm's legacy dist.shasum).
func SHA1Hex(b []byte) string {
	sum := sha1.Sum(b)
	return hex.EncodeToString(sum[:])
}

// SHA512SRI returns the SRI form ("sha512-<base64>") of b, as written into
// packuments generated by `depshelf import npm`.
func SHA512SRI(b []byte) string {
	sum := sha512.Sum512(b)
	return "sha512-" + base64.StdEncoding.EncodeToString(sum[:])
}
